version: '1.0'
services:
  sistema-prueba:
    build: .
    restart: always
    # container_name: front_sistema_prueba_v2
    ports:
      - '3300:3300'
    networks:
      - sistema_relojes_default

networks:
  sistema_relojes_default:
    name: sistema_relojes_default
