version: '3.8'

services:
  sistema-prueba:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front_sistema_prueba
    restart: unless-stopped
    ports:
      - '3500:3500'
    networks:
      - prueba
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3500"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  prueba:
    name: prueba
    driver: bridge
