version: '1.0'
services:
  sistema-prueba:
    build: .
    restart: always
    # container_name: front_sistema_prueba_v2
    ports:
      - '3300:3300'
    networks:
      - api_sistema_mantenimiento_default

networks:
  api_sistema_mantenimiento_default:
    name: api_sistema_mantenimiento_default
    external: true
